version: '3.8'

services:
  new_php:
    build:
      context: .
    container_name: php8
    restart: always
    volumes:
      - ./:/app
  werver:
    container_name: www.php8.dev
    image: nginx:1.19.2-alpine
    ports:
      - 9087:80
    volumes:
      - ./.docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - new_php
